// This script was generated by the Dialogue Converter tool.
// 1. Place this script in a folder named "Editor" inside your Assets folder.
// 2. A new menu item "Dialogue Tools > Create News Asset" will appear.
// 3. Click it to generate your Dialogue.asset file.

using UnityEngine;
using UnityEditor;

public class NewsCreator
{
    [MenuItem("Dialogue Tools/Create News Asset")]
    public static void CreateDialogueAsset()
    {
        // Create a new Dialogue asset instance
        Dialogue dialogue = ScriptableObject.CreateInstance<Dialogue>();

        dialogue.npcName = "News";

        // Populate the dialogue lines
        dialogue.lines = new DialogueLine[]
        {
            new DialogueLine { speaker = Speaker.NPC, sentence = "We interrupt this program with some breaking news." },
            new DialogueLine { speaker = Speaker.NPC, sentence = "Toxic clouds continue to spread across the town of Bayside, putting its citizens at risk." },
            new DialogueLine { speaker = Speaker.NPC, sentence = "The govern-" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "It really is in every channel, huh?" },
            new DialogueLine { speaker = Speaker.NPC, sentence = "-all of the citizens of Bayside to evacuate the city at once." },
            new DialogueLine { speaker = Speaker.NPC, sentence = "Meanwhile, neighboring towns have gathered together to protest in unison against Continuity Industries." },
            new DialogueLine { speaker = Speaker.NPC, sentence = "And as of this moment, Continuity Industries has yet to release any official (/public) statements rega-" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "What an amazing start to my CEO life." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Tell me, bear." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "What do I do?" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Everyone’s blaming my company." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "No–worse–they’re blaming me." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Dad told me this job would be easy." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Approve this, approve that." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Everything was going well until that stupid project came along..." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Fund and develop our own chemical manufacturing plant in Bayside." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Then the leak…" },
            new DialogueLine { speaker = Speaker.NPC, sentence = "Player ruffles his hair or something in distress" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Why am I being blamed for this!?" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "How was I supposed to know that might happen?" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "I didn’t even understand what was written in the reports!" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "This is why I hired people to worry about these stupid problems for me!" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "They even said this entire thing was foolproof!" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "It’s their fault for not finding and fixing the issues." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "All I did was fund the project…" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Yeah, it’s not my fault." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "I mean…" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "I kind of knew the risks of accepting such a partnership, (/project)," },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "From such a small company." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "So I guess…I’m partially responsible for what happened." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "…" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "It’s okay, dad told me not to worry about it." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Accidents happen all the time, right?" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Like he always said." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "The road isn’t always straight, yeah I’m just at an incline right now…" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "All I need to do is wait it out…" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Nobody told me being a CEO would be so complicated." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Can’t our company just make wooden bear sculptures instead?" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "It’s easier, no need to think too much into it." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Carve out tiny bears like the one I made right here and…" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "and…" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "I’ve been talking to a figurine I made this entire time, haven’t I?" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "…Great." },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Well, since I’m not getting any calls, maybe…" },
            new DialogueLine { speaker = Speaker.PLAYER, sentence = "Maybe a quick nap wouldn’t hurt." }
        };

        // Create the asset file in the project
        string path = "Assets/News.asset";
        AssetDatabase.CreateAsset(dialogue, path);
        AssetDatabase.SaveAssets();

        EditorUtility.FocusProjectWindow();
        Selection.activeObject = dialogue;

        Debug.Log($"Dialogue asset created at: {path}");
    }
}